---
apiVersion: v1
kind: Secret
metadata:
  name: perses-basic-auth
  namespace: perses-dev
data:
  password: cGFzc3dvcmQxMjM=
---
apiVersion: perses.dev/v1alpha2
kind: PersesDatasource
metadata:
  name: perses-datasource-basic-auth-sample
  namespace: perses-dev
spec:
  client:
    basicAuth:
      type: secret
      name: perses-basic-auth
      username: testuser
      password_path: password
    tls:
      enable: true
      insecureSkipVerify: true
  config:
    display:
      name: 'Basic Auth Datasource'
    default: false
    plugin:
      kind: 'PrometheusDatasource'
      spec:
        directUrl: 'https://prometheus.demo.prometheus.io'
