---
apiVersion: v1
kind: Secret
metadata:
  name: encrypted-data-key
  namespace: perses-dev
data:
  data-key: 3v8/m+zwjw45TKd5NGt8JrSA48ZI27rKiEFn5Kpaegw=
---
apiVersion: perses.dev/v1alpha2
kind: Perses
metadata:
  name: perses-provisioning-sample
  namespace: perses-dev
spec:
  metadata:
    labels:
      instance: perses-provisioning-sample
  config:
    database:
      file:
        folder: '/perses'
        extension: 'yaml'
    security:
      encryption_key_file: /etc/perses/provisioning/secrets/encrypted-data-key-data-key
      cookie:
        secure: false
      enable_auth: false
      readonly: false
  provisioning:
    secretRefs:
      - name: encrypted-data-key
        key: data-key

