## Append samples you want in your CSV to this file as resources ##
resources:
  - perses.dev_v1alpha1_perses.yaml
  - perses.dev_v1alpha1_persesdashboard.yaml
  - perses.dev_v1alpha1_persesdatasource.yaml
  - perses.dev_v1alpha2_perses.yaml
  - perses.dev_v1alpha2_persesdashboard.yaml
  - perses.dev_v1alpha2_persesdatasource.yaml
  - perses.dev_v1alpha2_persesglobaldatasource.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
