# This configuration is for teaching kustomize how to update name ref substitution
nameReference:
  - kind: Issuer
    group: cert-manager.io
    fieldSpecs:
      - kind: Certificate
        group: cert-manager.io
        path: spec/issuerRef/name

# This configuration tells kustomize to apply namePrefix to Certificate secretName
namePrefix:
  - path: spec/secretName
    kind: Certificate
    group: cert-manager.io

# This configuration is for teaching kustomize how to do variable substitution
varReference:
  - path: spec/dnsNames
    kind: Certificate
