name: go
on:
  push:
    branches:
      - main
      - release/*
      - snapshot/*
    tags:
      - v*
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.ref_name != 'main' }}

jobs:
  changed-files:
    uses: ./.github/workflows/changed-files.yaml
  gofmt:
    needs: changed-files
    if: ${{ needs.changed-files.outputs.non-markdown-files }}
    name: "check code format"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - uses: perses/github-actions@v0.11.0
      - uses: ./.github/perses-ci/actions/setup_environment
        with:
          enable_go: true
      - name: check format
        run: make checkformat || (echo "Please run 'make format' locally and commit the changes." && exit 1)
      - name: verify go modules
        run: make tidy
  test-unit:
    needs: changed-files
    if: ${{ needs.changed-files.outputs.non-markdown-files }}
    name: "unit tests"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - uses: perses/github-actions@v0.11.0
      - uses: ./.github/perses-ci/actions/setup_environment
        with:
          enable_go: true
      - name: unit tests
        run: make test-unit
  test-integration:
    needs: changed-files
    if: ${{ needs.changed-files.outputs.non-markdown-files }}
    name: "integration tests"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - uses: perses/github-actions@v0.11.0
      - uses: ./.github/perses-ci/actions/setup_environment
        with:
          enable_go: true
      - name: integration tests
        run: make test-integration
  lint-api:
    needs: changed-files
    if: ${{ needs.changed-files.outputs.non-markdown-files }}
    name: "kube-api-linter"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - uses: perses/github-actions@v0.11.0
      - uses: ./.github/perses-ci/actions/setup_environment
        with:
          enable_go: true
      - name: lint API types
        run: make lint-api
  lint:
    needs: changed-files
    if: ${{ needs.changed-files.outputs.non-markdown-files }}
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - uses: perses/github-actions@v0.11.0
      - uses: ./.github/perses-ci/actions/setup_environment
        with:
          enable_go: true
          enable_go_cache: false
          enable_npm: false
      - name: generate files
        run: make generate
      - name: check bundle changes
        run: make bundle-check
      - name: check installer manifest is up-to-date
        run: make installer-check
      - name: golangci-lint
        run: make lint
